services:
  - type: web
    name: tradeapp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    pythonVersion: 3.12.7
    rootDir: backend
  - type: web
    name: tradeapp-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    rootDir: frontend
